plugins:
  - '@dotcom-tool-kit/circleci'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/prettier'
  - '@dotcom-tool-kit/lint-staged-npm'
  - '@dotcom-tool-kit/npm'
  - '@dotcom-tool-kit/circleci-npm'
hooks: {}
options:
  '@dotcom-tool-kit/jest':
    configPath: './jest.config.js'
