plugins:
  - '@dotcom-tool-kit/jest'
  - '@dotcom-tool-kit/circleci'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/prettier'
  - '@dotcom-tool-kit/npm'
  - '@dotcom-tool-kit/circleci-npm'
hooks:
  test:local:
    - Eslint
    - JestLocal
  test:ci:
    - Eslint
    - JestCI
options:
  '@dotcom-tool-kit/jest':
    configPath: './jest.config.js'