plugins:
  - '@dotcom-tool-kit/frontend-app'
  - '@dotcom-tool-kit/jest'
  - '@dotcom-tool-kit/circleci'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/prettier'
  - '@dotcom-tool-kit/nodemon'
  - '@dotcom-tool-kit/lint-staged'
  - '@dotcom-tool-kit/husky-npm'
  - '@dotcom-tool-kit/circleci-npm'
hooks:
  run:local:
    - Nodemon
  test:local:
    - Eslint
    - JestLocal
  test:ci:
    - Eslint
    - JestCI
options:
  '@dotcom-tool-kit/jest':
    configPath: './jest.config.js'
  '@dotcom-tool-kit/prettier':
    files: '**/*.{js,jsx,yml,json}'
    configFile: './prettier.config.js'
  '@dotcom-tool-kit/eslint':
    files: '**/*.{js,jsx,yml,json}'
  '@dotcom-tool-kit/circleci':
    nodeVersion:
      - '18.16'
  '@dotcom-tool-kit/nodemon':
    entry: './demos/app.js'
    useVault: false
    ports: [5005]
