plugins:
  - '@dotcom-tool-kit/jest'
  - '@dotcom-tool-kit/circleci'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/prettier'
  - '@dotcom-tool-kit/npm'
  - '@dotcom-tool-kit/circleci-npm'
hooks:
  test:local:
    - Eslint
    - JestLocal
  test:ci:
    - Eslint
    - JestCI
options:
  '@dotcom-tool-kit/jest':
    configPath: './jest.config.js'
  '@dotcom-tool-kit/prettier':
    files: '**/*.{js,yml,json}'
  '@dotcom-tool-kit/eslint':
    files: '**/*.{js,yml,json}'
  '@dotcom-tool-kit/circleci':
    nodeVersion:
      - '18.16'
